### ISSUE TITLE
Can't send a message to a direct channel

### ISSUE THREAD

**Issue by yegor256** [Itiviti/simple-slack-api#157]
This is what I'm doing:

```java
SlackChannel channel = session.findChannelById("D3Q1Z1BS7");
session.sendMessage(channel, "hello, world!");
```

This code works fine if the channel is **not** direct. However, if it's direct nothing really happens. No exceptions and no message in the channel. However, this code works fine with the same direct channel:

```java
SlackMessagePosted event = //...
SlackChannel channel = event.getChannel();
session.sendMessage(channel, "hello, world!");
```

Is it a bug or I'm doing something wrong?

**Comment by bcorne** [comment]
Hi, are you sure of the id of the channel you are using? how did you get the id? when you're looking into the session for the channel is it found?

**Comment by yegor256** [comment]
@bcorne yes, it's found, as far as I can tell: `findChannelById()` returns an instance of `SlackChannel`.

**Comment by yegor256** [comment]
@bcorne I suspect that the object of class `SlackChannel` returned by `SlackMessagePosted.getChannel()` is not the same as the object returned by `SlackSession. findChannelById()`. There is some difference in them and that's why `sendMessage()` doesn't work in one case.

**Comment by bcorne** [comment]
ok, I'll have a look at that then

**Comment by yegor256** [comment]
@bcorne any progress here? Sorry to bother you, but it's a real blocker for us. Thanks!

**Comment by yegor256** [comment]
This is my workaround:

```
session.sendMessage(
  session.openDirectMessageChannel(
    session.findUserByUserName("yegor256")
  ).getReply().getSlackChannel(),
  "hello, world"
);
```

**Comment by moults31** [comment]
This has been fixed by a redesign of Slack's backend. Now instead of direct channels of form `D1234ABCD`, you can directly call sendMessage on channels of forms:
- `U1234ABCD` (user ID for a direct message to a single user)
- `C1234ABDC` (channel ID for a direct message to multiple users)

Please see https://github.com/moults31/cs427group20-simple-slack-api-tests - specifically sendDirectMessageLocalDate - for a sample that proves this use case. Feel free to ping me for usage tips if the README is insufficient. You will need your own slack app to use my test suite.

How to get Channel IDs or User IDs from your workspace: https://stackoverflow.com/questions/40940327/what-is-the-simplest-way-to-find-a-slack-team-id-and-a-channel-id

@yegor256 if you are still using simple-slack-api you may find this useful.

**Comment by yegor256** [comment]
@moults31 thanks!
